export const API_ENDPOINTS = {
  LOGIN: "login",
  REGISTER: "register",
  FORGOT_PASSWORD: "password/forgot",
  USERS: "users",
  USERS_COMMON: "common/user",
  GROUPS: "groups",
  CHANGE_PROFILE_PASS: "profile/password",
  UPDATE_PROFILE: "profile",
  COMPANY: "company",
  COMPANY_SHIFT: "company/shift",
  STATISTICS: "statistics",
  STATISTICS_SETUP: "statistics/setup",
  STATISTICS_DASHBOARD: "statistics/dashboard",
  JOB_TITLE: "jobTitle",
  DEPARTMENT: "department",
  USER_HIERARCHY: "hierarchy",
  USER_HIERARCHY_CHART: "hierarchy/chart",
  USER_HIERARCHY_USERS: "hierarchy/user-list",
  FMS_TEMPLATE: "fms/templates",
  FMS_AI_WORKFLOW_GENERATE_FIELDS: "ai/fields",
  FMS_AI_WORKFLOW_GENERATE_TEMPLATE: "ai/templete",
  FMS_INDENT: "fms/indent",
  FMS_INDENT_LISTS: "fms/indent/submitted-list",
  FMS_STEP: "fms/step",
  UPDATE_FMS_STEP: "fms/steps",
  AUTH_EMAIL_VERIFY: "verify-email",
  AUTH_RESEND_VERIFICATION: "verify-email",
  ROLES: "roles",
  ROLE_PERMISSIONS: "roles/role-permission",
  NOTIFICATION: "common/notifcation",
  TASKS: "task",
  TASK_DETAIL: "task/detail",
  TASK_UPDATE: "task/update",
  TASK_DELETE: "task/delete",
  COMMON_UPLOAD: "common/upload",

  CHANGE_PASSWORD: "auth/change-password",
  User_Update_Account: "user/update-account",
  User_Cancel_Subscription: "user/cancel-subscription",
  Auth_Contact: "/auth/contact",
  Auth_Profile_View: "/auth/profile/view",
  User_GetProfileList: "/user/get-profile-list",
  Auth_Pageviews_Analytics: "/auth/pageviews-analytics",
  Auth_Request_Verify_Email: "/auth/request-verify-email",
  Auth_Verify_Email: "/auth/verify-email",
  User_Contact: "/user/contact",
  RESET_PASSWORD: "password/reset",
  AUTH_VERIFY_INVITE: "auth/invite",
  FMS_INDENT_DRAFT_LIST: "fms/indent/draft-list",
  FMS_INDENT_DRAFT_LIST_DETAILS: "fms/indent",
  FMS: "fms/indent/submitted-list",
  FMS_DETAIL: "fms/indent/with-steps",
  AUDIT_LOGS: "auditLogs",
  TASK_TEMPLATE: "task/templete/",
  UPDATE_DEVICE_TOKEN: "common/updateDeviceToken",
  FMS_EXPORT: "export",
  FMS_GANTT_CHART_SHARE: "fms/gantt-chart-share",
  COMPANY_LOCATION: "company/location",
  COMPANY_HOLIDAY: "company/holiday",
  COMPANY_HOLIDAY_ME: "company/holiday/me",
  COMPANY_HOLIDAY_DETAIL: (id: string) => `company/holiday/${id}`,
  COMPANY_HOLIDAY_STATUS: (id: string) => `company/holiday/${id}/status`,
  COMPANY_HOLIDAY_CANCEL: (id: string) => `company/holiday/${id}/cancel`,
  COMPANY_CALENDAR: "company/calendar",
  COMPANY_CALENDAR_DETAIL: (id: string) => `company/calendar/${id}`,
  COMPANY_CALENDAR_HOLIDAYS: "company/calendar/holidays",
  FMS_GANTT_CHART: "fms/gantt-chart",
  FMS_GANTT_CHART_VIEW: "gantt-chart/view",
  NOTIFICATION_COUNT: "common/notifcation-count",
  FMS_CANCEL: "fms/indent",
  FMS_INDENT_SHARE: "fms/indent-share",
  FMS_INDENT_BY_TOKEN: "fms-indent",
  REPORTS: "report/fms",
  /** FMS report email/automated schedules */
  FMS_REPORT_SCHEDULE: "report/fms/schedule",
  ANALYTICS: "analytic",
  FMS_SEARCH: "common/fms-templete/search",
  STEP_SEARCH: "common/steps/search",
  REFERENCE_CODE_SEARCH: "common/indent/search",
  DOER_SEARCH: "common/user/search",
  COMMON_ROLES_PERMISSIONS: "common/role-permmsion-list",
  PUBLIC_FMS_INDENT: "fms-indent",
  USER_STORAGE: "users/storage",
  SUPPORT_TICKET: "support-ticket",
  COMPANY_AUDIT: "company-audit",
  SUBSCRIPTION: "subscription",
  COMPANY_SUBSCRIPTION: "company/subscription",
  /** Social feed posts (CRUD + current user by status) */
  SOCIAL_POSTS: "social/posts",
  SOCIAL_POSTS_MEDALS: "social/posts/medals",
  SOCIAL_POSTS_MEDALS_LEADERBOARD: "social/posts/medals/leaderboard",
  SOCIAL_REACTIONS_TOGGLE: "social/reactions/toggle",
  SOCIAL_COMMENTS: "social/comments",
  SOCIAL_COMMUNITIES: "social/communities",
  SOCIAL_COMMUNITIES_EXPLORE: "social/communities/explore",
  SOCIAL_COMMUNITIES_JOINED: "social/communities/joined",
  SOCIAL_COMMUNITIES_REQUEST: "social/communities/request",
  /** Sticky notes */
  STICKY_NOTES: "sticky-notes",

  /** Vault */
  VAULT_SECURITY_SETUP: "vault/security/setup",
  VAULT_SECURITY_STATUS: "vault/security/status",
  VAULT_VERIFY_KEY: "vault/verify-key",
  VAULT: "vault",
  VAULT_USERS: "vault/users/list",
  VAULT_SHARE: "vault/share",
  VAULT_DETAIL: (id: string) => `vault/${id}`,
  VAULT_RESET_SECURITY: "vault/reset-security",
};
