export const API_ENDPOINTS = {
  USERS: "users",
  USERS_COMMON: "common/user",
  GROUPS: "groups",
  CHANGE_PROFILE_PASS: "profile/password",
  UPDATE_PROFILE: "profile",
  COMPANY: "company",
  COMPANY_SHIFT: "company/shift",
  COMPANY_LOCATION: "company/location",
  COMPANY_HOLIDAY: "company/holiday",
  COMPANY_HOLIDAY_ME: "company/holiday/me",
  COMPANY_HOLIDAY_DETAIL: (id: string) => `company/holiday/${id}`,
  COMPANY_HOLIDAY_STATUS: (id: string) => `company/holiday/${id}/status`,
  COMPANY_HOLIDAY_CANCEL: (id: string) => `company/holiday/${id}/cancel`,
  COMPANY_CALENDAR: "company/calendar",
  COMPANY_CALENDAR_DETAIL: (id: string) => `company/calendar/${id}`,
  COMPANY_CALENDAR_HOLIDAYS: "company/calendar/holidays",
  COMPANY_AUDIT: "company-audit",
  COMPANY_SUBSCRIPTION: "company/subscription",
  STATISTICS_SETUP: "statistics/setup",
  JOB_TITLE: "jobTitle",
  DEPARTMENT: "department",
  USER_HIERARCHY: "hierarchy",
  USER_HIERARCHY_CHART: "hierarchy/chart",
  USER_HIERARCHY_USERS: "hierarchy/user-list",
  ROLES: "roles",
  ROLE_PERMISSIONS: "roles/role-permission",
  AUDIT_LOGS: "auditLogs",
  COMMON_ROLES_PERMISSIONS: "common/role-permmsion-list",
  USER_STORAGE: "users/storage",
  SUPPORT_TICKET: "support-ticket",
  COMMON_UPLOAD: "common/upload",
  CHANGE_PASSWORD: "auth/change-password",
  SUBSCRIPTION: "subscription",
};
